title: 蒲田書道教室
description: 東京都蒲田にある書道教室のホームページ
theme: jekyll-theme-primer

plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-gist
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

exclude:
  - node_modules
encoding: utf-8
